[[keyboard.bindings]]
key="Space"
mods="Control"
mode="Vi"
action="ScrollToBottom"

[[keyboard.bindings]]
key="Space"
mods="Control"
action="ToggleViMode"

[scrolling]
history=10000
multiplier=3

[bell]
animation = "EaseOutExpo"
color = "#FFFFFF"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"


[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
builtin_box_drawing = true
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window.padding]
x = 6
y = 3

[window.dimensions]
columns = 80 # Columns wide
lines = 27 # Columns high

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background= '0x161616'
foreground= '0xf2f4f8'

[colors.cursor]
text= '0x000000'
cursor= '0xffffff'

[colors.normal]
black=   '0x282828'
red=     '0xee5396'
green=   '0x25be6a'
yellow=  '0x08bdba'
blue=    '0x78a9ff'
magenta= '0xbe95ff'
cyan=    '0x33b1ff'
white=   '0xdfdfe0'

[colors.bright]
black=   '0x484848'
red=     '0xf16da6'
green=   '0x46c880'
yellow=  '0x2dc7c4'
blue=    '0x8cb6ff'
magenta= '0xc8a5ff'
cyan=    '0x52bdff'
white=   '0xe4e4e5'

